services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${OUTER_BOT_PORT}:${INNER_BOT_PORT}"
    env_file:
      - .env
    networks:
      - nw

networks:
  nw:
    driver: bridge